ARG ELK_VERSION

FROM docker.elastic.co/beats/metricbeat-oss:${ELK_VERSION}
#COPY metricbeat/metricbeat1.yml /usr/share/metricbeat/metricbeat1.yml
USER root 
#RUN chown root /usr/share/metricbeat/metricbeat1.yml